United-Programming/UPBot

.gitignore
UPBot Code/Program.cs

Added properties to Gitignore and removed token

🔒️ Removed token

---

UPBot Code/Commands/HelpLanguages.cs

this command allows to new users find good tutorials on YouTube. Included tutorials: C#, C++, Phyton, Java. I guess this is enough for coding games or other stuff.

Useful Command for new users

---

UPBot Code/Commands/Ping.cs

Ffor the same user and globally.

🩹 Now the message is never the same of the last one

---

UPBot Code/Commands/Game.cs

Added 2 working game commands
bool and rps

Slicendice

---

UPBot Code/Commands/Delete.cs

Added the Delete.cs file to deal with the 'delete' command, which is supposed to delete the last x messages from a specific user.

Added 'delete' command

---

UPBot Code/Commands/HelpLanguages.cs
UPBot Code/Commands/Refactor.cs

Jonathan branch

---

UPBot Code/Commands/Delete.cs

- It can delete the last x messages of any user.
- It sets the limit of the messages you can delete at a time to 50.
- It has a command overload for the functionality of deleting the last x messages of a specified user. The functionality has not been implemented yet.
- Added summary to the class and methods.

Added functionality to 'delete' command.

---

UPBot Code/Commands/Delete.cs
UPBot Code/UtilityFunctions.cs

- Added callback for the successful execution of the 'delete' command, containing some information about the execution, like how many messages have been deleted and the user whose messages have been deleted if specified. This functionality is located in a separate function.
- Added UtilityFunctions.cs as a (static) class that contains "general-purpose" functions that every command or part of the bot could need (not bound to a specific command). It is a static class and therefore all functions should be static.

'delete' command success-callback and Utility Functions

---

UPBot Code/Commands/Delete.cs

- Added functionality of deleting the last x messages of a specific user. Earlier, you could only delete the last x messages (no matter which user). Now both functionalities are included.
- Split the process of deleting the messages into a separate function.
- If you try to delete the last 0 or [insert negative number] messages, the bot will yell at you. Try it and see what happens.

Last iterations of 'delete' command

---

UPBot Code/Commands/Delete.cs

- Added a summary to the recently created 'DeleteCommand' function, which is responsible for the core-process of deleting a message without any other functionality (which is located in the functions that call this 'DeleteCommand' function). This is the function I mentioned in the last commit.

Added summary to recently created 'DeleteCommand' function

---

UPBot Code/Commands/Delete.cs
UPBot Code/Commands/HelpLanguages.cs
UPBot Code/Commands/Refactor.cs

- Added <summary> opening tag to main summary
- Left only one GenerateHelpfulAnswer() function, instead of 5 very similar ones to avoid unnecessary duplicate code. The method still yields the correct results due to the use of Dictionaries and other ways to display the correct value.
- Generally a lot of cleaning up and optimizing.
PLEASE TAKE A DEEP LOOK AT ALL THE CHANGES, SINCE IT'S A MASSIVE CHANGE.

Refactor 'helplanguages' command ('HelpLanguages.cs')

---

UPBot Code/Commands/Refactor.cs
UPBot Code/UtilityFunctions.cs

Added a unprivileged CheckLanguage and a Privileged refactor.

---

UPBot Code/Commands/CustomCommand.cs
UPBot Code/Commands/CustomCommandsService.cs
UPBot Code/Program.cs
UPBot Code/UtilityFunctions.cs
UPBot.csproj

- Added two classes for the 'Custom Commands' feature with a big part of the functionality.
- Added new NuGet package dependency to be able to wait for one's next message (NuGet package name: DSharpPlus.Interactivity)
- Cleaned 'UtilityFunctions' up
- Added summary
- Removed redundant spaces/empty lines
- Removed unused `using`-statement

"Custom commands" work-in-progress and cleaning up

---

UPBot Code/Commands/Refactor.cs
UPBot Code/Program.cs

Removed unused `using`-statement in Program.cs

Removed unused `using`-statement in Program.cs

---

UPBot Code/Commands/CustomCommandsService.cs
UPBot Code/Commands/Delete.cs
UPBot Code/UtilityFunctions.cs

- Added function 'BuildEmbedAndExecute' in 'UtilityFunctions.cs' to build an embed and execute it right away (please refer to the summary for more information)
- Added function 'LogEmbed' in 'UtilityFunctions.cs' to execute an embed (send as a message). Please refer to the summary for more information
- Added new CommandError
- Added embeds to Custom Commands callbacks
- Added new common color (LightBlue)

Added embeds to CustomCommandsService.cs callbacks

---

UPBot Code/UtilityFunctions.cs

- Added and edited summary of 'PluralFormatter' function in 'UtilityFunctions.cs'

Summary 'PluralFormatter' function in 'UtilityFunctions.cs'

---

UPBot Code/Program.cs

- Fixed indentation in Program.cs

Fixed indentation in Program.cs

---

UPBot Code/Commands/CustomCommandsService.cs

- Added some information about the accessibility of the CC commands (only Mod)

Addendum to command descriptions

---

UPBot Code/Commands/BannedWords.cs
UPBot Code/Commands/CustomCommandsService.cs

- Just some small changes, too small to be mentioned

Small changes to description

---

UPBot Code/Commands/WhoIs.cs

- Added description to 'whois' command
- Changed the code in 'WhoIs.cs' to use the 'BuildEmbed' utility function, instead of doing everything manually. Code has been cleaned up.

Edited WhoIs.cs

---

UPBot Code/Commands/HelpLanguages.cs

- Please take care of what you commit and avoid typos :)

Changed redundant character in 'HelpLanguages.cs'

---

UPBot Code/Commands/Game.cs
UPBot Code/Commands/HelpLanguages.cs
UPBot Code/Commands/Stats.cs

- Optimized and reworked the 'helplanguage' command with a few simplifications and optimizations regarding readability, accessibility and performance (for example, not 3 Dictionaries anymore, but one Dictionary with a ContainerClass 'LanguageInfo' for all the information about the language (course link, video link, color)
Everything has been tested and it seems to work so far

Optimized and reworked the 'HelpLanguages.cs' file

---

UPBot Code/Commands/Game.cs

* Game.cs was trying to use UtilityFunctions nstead of Utils.

🐛 Fix UtilityFunctions issue

---

ToDo.txt
UPBot Code/Actions/AppreciationTracking.cs
UPBot Code/Database.cs
UPBot Code/Program.cs

We may need to do some merges here.

All changes from CPU local branch

---

UPBot Code/Program.cs
UPBot Code/Utils.cs

Updated version and made sure you get a valid error if you forgot the bot token as parameter

Updated version and warning if bot token is missing

---

UPBot Code/Commands/Tag.cs

It has two bugs, one in list and one when you type 43 color (random color) it appear fake error. (Color randomising works but for some reason bot think there error).

More features for Tag.cs

---

UPBot Code/Commands/Tag.cs
UPBot Code/DataClasses/TagBase.cs

Fixed: Sorting in tags, added another variable to save in TagBase.cs!

Added ability to add/remove thumbnails to tags.

---

UPBot Code/Commands/Stats.cs

It was "meber" before, changed it to "member".

Spelling of member corrected

---

UPBot Code/Utils.cs

* Release date set as of today

🔖 Update release date for 0.3.5

---

src/Utils.cs

* Revision remained set to c since some versions back
* Resetting to a

🔖 Fix revision

---

src/Utils.cs

* Been reset to c again
* Since out previous one has been a, setting to b

🔖 Fix revision letter
